CREATE DATABASE baitap2;

USE baitap2;

CREATE TABLE CUSTOMERS(
	CustomerId INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Age INT CHECK( Age > 0 )
);
