CREATE DATABASE baitap3;

USE baitap3;

CREATE TABLE CUSTOMERS(
	CustomerID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CustomerName VARCHAR(100)
);
CREATE TABLE ORDERS (
	Orders_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Orders_day DATETIME NOT NULL,
    Total_money DECIMAL(18,4) NOT NULL,
    CustomerID INT UNSIGNED NOT NULL,
    CONSTRAINT FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);

SELECT * FROM ORDERS;